// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Spotify.Core.Entities;

#nullable disable

namespace Spotify.Infrastructure.Data
{
    public partial class FeaturifyContext : IdentityDbContext<ApplicationUser>
    {
        public FeaturifyContext()
        {
        }

        public FeaturifyContext(DbContextOptions<FeaturifyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TrackEntity> Tracks { get; set; }
        public virtual DbSet<UserTrackEntity> UsersTracks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.TracksConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ApplicationRoleConfiguration());

            base.OnModelCreating(modelBuilder);
        }
    }
}
