// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Spotify.Core.Data.Configurations;
using Spotify.Core.Model;
using System;

#nullable disable

namespace Spotify.Core.Data
{
    public partial class FeaturifyContext : DbContext
    {
        public FeaturifyContext()
        {
        }

        public FeaturifyContext(DbContextOptions<FeaturifyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FavoritesTracks> FavoritesTracks { get; set; }
        public virtual DbSet<Tracks> Tracks { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Featurify;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.FavoritesTracksConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TracksConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
