// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Spotify.Core.Model
{
    public partial class Tracks
    {
        public int Id { get; set; }
        public string AlbumIdSpotify { get; set; }
        public string TrackIdSpotify { get; set; }
        public string ArtistIdSpotify { get; set; }
        public string TrackName { get; set; }
    }
}