// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Spotify.Core.Model
{
    public partial class Users
    {
        public int Id { get; set; }
        public string Email { get; set; }
    }
}