// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Featurify.Core.Entities;

namespace Featurify.Infrastructure.Data.Configurations
{
    public partial class TracksConfiguration : IEntityTypeConfiguration<TrackEntity>
    {
        public void Configure(EntityTypeBuilder<TrackEntity> entity)
        {
            entity.Property(e => e.AlbumIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ArtistIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TrackIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TrackName)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TrackEntity> entity);
    }
}
