// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spotify.Core.Entities;

namespace Spotify.Infrastructure.Data2.Configurations
{
    public partial class UsersTracksConfiguration : IEntityTypeConfiguration<UserTrackEntity>
    {
        public void Configure(EntityTypeBuilder<UserTrackEntity> entity)
        {
            entity.HasIndex(e => e.TrackId, "IX_UsersTracks_TrackId");

            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.Track)
                .WithMany(p => p.UsersTracks)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersTracks_Tracks");

            entity.HasOne(d => d.User) // current
                .WithMany(p => p.UsersTracks) // orm 
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersTracks_AspNetUsers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserTrackEntity> entity);
    }
}
