// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Spotify.Core.Models
{
    public partial class FavoritesTracks
    {
        public int Id { get; set; }
        public string UsuarioId { get; set; }
        public string TrackId { get; set; }
    }
}