// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Featurify.Core.Entities
{
    public partial class TrackEntity
    {
        public TrackEntity()
        {
            UsersTracks = new HashSet<UserTrackEntity>();
        }

        public int Id { get; set; }
        public string AlbumIdSpotify { get; set; }
        public string TrackIdSpotify { get; set; }
        public string ArtistIdSpotify { get; set; }
        public string TrackName { get; set; }

        public virtual ICollection<UserTrackEntity> UsersTracks { get; set; }
    }
}