// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Spotify.Core.Data;
using Spotify.Core.Models;
using System;


namespace Spotify.Core.Data.Configurations
{
    public partial class TracksConfiguration : IEntityTypeConfiguration<Tracks>
    {
        public void Configure(EntityTypeBuilder<Tracks> entity)
        {
            entity.ToTable("tracks");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.AlbumIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ArtistIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TrackIdSpotify)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TrackName)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tracks> entity);
    }
}
